### ISSUE TITLE
Crash When Using Factory Manager

### ISSUE THREAD

**Issue by ThatBenderGuy** [gigabit101/StevesFactoryManager#79] opened 2019-09-10 03:07 UTC
So when right clicking the factory manager when there are the pipe cables next to it the game crashes with this error:

```
The game crashed whilst exception in server tick loop
Error: java.lang.AbstractMethodError: Method vswe/stevesfactory/blocks/manager/FactoryManagerTileEntity.getPos()Lnet/minecraft/util/math/BlockPos; is abstract
```

**Comment by hnOsmium0001** [comment] 2019-09-11 01:33
Can you post the full crash report/log? Either on https://pastebin.com or https://gist.github.com is fine

**Comment by hnOsmium0001** [comment] 2019-09-16 01:07
@ThatBenderGuy Can you please try the latest version and see if this issue still exists? Because currently I can't reproduce this issue.

**Comment by Austin5003** [comment] 2019-09-23 03:22
Still occurring in the latest alpha
[crash-2019-09-22_23.17.26-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/3640520/crash-2019-09-22_23.17.26-server.txt)

**Comment by hnOsmium0001** [comment] 2019-09-23 04:12
To be honest I have no idea why doe this happen... `getPos` should be implemented in `TileEntity` already. I added another implementation of `getPos` in, that should fix it.
If that still don't to the thing, I am helpless

---
Added after testing:
I think I know why that happens: I have a set of method in an interface (`INetworkController`) and they are implemented in `TileEntity`, so I didn't implement them in factory manager tile. This works fine in the userdev environment because the method names match, however in production (obfuscated environment) the method names become different.
This should be fixed in `alpha12`.

**Closed as completed** 2019-09-23 16:46 UTC
Labels: bug, 1.14+
