### ISSUE TITLE
Problem with fluids

### ISSUE THREAD

**Issue by Grovert11** [gigabit101/StevesFactoryManager#32] opened 2016-12-17 17:00 UTC
After trying to manipulate some fluids, my world keeps crashing with the following crash report:
http://pastebin.com/bDeRReKx

**Comment by Grovert11** [comment] 2016-12-17 18:08
Oh also, while experimenting dome more, I noticed I'm not able to move liquids around at all. The crash seems to be happening when using a fluid condition.

**Comment by SaMoSe12** [comment] 2016-12-18 03:55
Well I don't know if it's the same case as mine, but if you try to use any fluid interaction with the ender io tank it would crash but with the tank from tinker's it worked great.

**Comment by Grovert11** [comment] 2016-12-18 11:23
Which versions are you using and could you send screenshots of how you're interacting eith the tanks? I can't get it to work

**Comment by SaMoSe12** [comment] 2016-12-18 19:48
Sure thing, http://imgur.com/a/GAjH4

**Comment by Grovert11** [comment] 2016-12-18 21:20
Thanks a bunch for the screenshots. I have been testing and found that the crash only happens when trying to do a fluid condition on an EnderIO tank. Also, inputting and outputting to the EnderIO tank don't work.

**Comment by SaMoSe12** [comment] 2016-12-19 04:41
Did some more experiments, you are totally right. 
But any type of condition will cause the crash.

**Comment by Grovert11** [comment] 2016-12-19 08:26
For me conditions worked, at least for the seared tank from Tinkers' Construct. I'll test with some more tanks later, but yesterday that worked

**Comment by SaMoSe12** [comment] 2016-12-19 09:40
Oh no on the Ender IO tank, I tried with fluid, redstone and common conditions and it crashed every time. with the Tinker's tank it worked great so far. 
The ex nihilo tank also works.
The Lava Generator from Simple Generators it's another example of the tank not working. 

I don't understand why it works in some mods, and in others not.

**Comment by Grovert11** [comment] 2016-12-19 14:28
It's weird. Let's hope for a fix soon!

**Comment by gigabit101** [comment] 2016-12-20 15:55
Yes I know read change logs there Is a issue with ender io tanks and sfm wait for 2.x for this to be fixed as it involves a massive rewrite of how sfm handles fluids

**Comment by gigabit101** [comment] 2016-12-20 15:56
This used to cause a crash bit I managed to catch it for now until 2.x is ready

**Comment by gigabit101** [comment] 2016-12-20 16:00
The problem is sfm old system used the Tank properties and not the to insert/ remove fluids so atm any mod that overwrites the properties are causing a crash this will be fixed in 2.x as I will be moving away from this system and using the new capabilities methods for fluids

**Comment by gigabit101** [comment] 2017-11-28 00:37
fixed in 1.12

**Closed as completed by gigabit101** 2017-11-28 00:37 UTC
Labels: bug, enhancement
