### ISSUE TITLE
[1.15.2] Crash keyPressed button

### ISSUE THREAD

**Issue by Rumaruka** [gigabit101/StevesFactoryManager#104] opened 2020-07-05 16:08 UTC
Crashlog - https://pastebin.com/2uuxJUTu
Version Forge - 31.2.30
Version mod - 4.0.0 alpha+build.3

**Comment by hnOsmium0001** [comment] 2020-07-05 17:19
Duplicate of #99

**Closed as completed by hnOsmium0001** 2020-07-05 17:19 UTC
Labels: bug, duplicate, 1.14+
